from __future__ import annotations

import os
import re
from pathlib import Path

import httpx

from models.fan import normalize_handle
from models.job import PublishResult
from services.redis_service import RedisService, redis_service


def slugify_creator(creator_handle: str) -> str:
    value = normalize_handle(creator_handle).strip("@").lower()
    return re.sub(r"[^a-z0-9_-]+", "-", value).strip("-") or "creator"


class Publisher:
    def __init__(self, redis_client: RedisService | None = None) -> None:
        self.redis = redis_client or redis_service
        self.output_dir = Path("output") / "published"

    async def publish_creator_report(self, creator_handle: str) -> PublishResult:
        creator = normalize_handle(creator_handle)
        try:
            fans = await self.redis.list_top_fans(creator, limit=15)
        except Exception:
            fans = []
        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / f"{slugify_creator(creator)}.md"

        lines = [
            f"# FanIQ Report: {creator}",
            "",
            "Generated by FanIQ for the Ship to Prod hackathon demo.",
            "",
            "## Top Fans",
            "",
        ]
        for index, fan in enumerate(fans, start=1):
            lines.extend(
                [
                    f"### {index}. {fan.display_name} ({fan.handle})",
                    "",
                    f"- Score: {fan.score}",
                    f"- Platforms: {', '.join(fan.platforms)}",
                    f"- Reason: {fan.reason}",
                    f"- Suggested action: {fan.suggested_action}",
                    f"- Source tool: {fan.source_tool}",
                    f"- Sources: {', '.join(fan.source_urls) if fan.source_urls else 'none'}",
                    "",
                ]
            )
        lines.extend(
            [
                "## Payment Status",
                "",
                "x402 payment rail: not enabled in local demo mode.",
                "",
            ]
        )
        path.write_text("\n".join(lines), encoding="utf-8")

        result = PublishResult(
            creator_handle=creator,
            published=True,
            url=str(path.as_posix()),
            payment_enabled=False,
            publisher="local",
            published_count=len(fans),
        )

        live_result = await self._try_senso_publish(creator, path, result)
        try:
            await self.redis.save_publish_result(live_result)
            await self.redis.push_sponsor_trace(
                creator,
                {
                    "sponsor": "cited.md/Senso",
                    "operation": live_result.publisher,
                    "detail": f"Published {live_result.published_count} profiles",
                },
            )
        except Exception:
            pass
        return live_result

    async def _try_senso_publish(self, creator: str, path: Path, fallback: PublishResult) -> PublishResult:
        api_key = os.getenv("SENSO_API_KEY")
        api_url = os.getenv("SENSO_API_URL")
        if not api_key or not api_url:
            return fallback
        try:
            async with httpx.AsyncClient(timeout=20) as client:
                response = await client.post(
                    api_url,
                    headers={"Authorization": f"Bearer {api_key}"},
                    json={
                        "title": f"FanIQ Report: {creator}",
                        "content": path.read_text(encoding="utf-8"),
                        "metadata": {"creator_handle": creator, "generated_by": "faniq"},
                    },
                )
                response.raise_for_status()
                data = response.json()
            fallback.publisher = "senso"
            fallback.url = data.get("url", fallback.url)
            return fallback
        except Exception:
            fallback.publisher = "local_fallback"
            return fallback


publisher = Publisher()
