from __future__ import annotations

from datetime import datetime, timezone

from models.fan import FanProfile, normalize_handle
from services.scorer import score_profile


def demo_fans(creator_handle: str = "@lexfridman", source_tool: str = "seed") -> list[FanProfile]:
    creator = normalize_handle(creator_handle)
    now = datetime.now(timezone.utc)
    rows = [
        {
            "handle": "@airesearcher_sf",
            "display_name": "Alex Chen",
            "bio": "AI researcher in San Francisco, writes about model evaluation and alignment.",
            "platforms": ["x", "linkedin"],
            "follower_count": 12400,
            "comment_count": 14,
            "reply_count": 9,
            "raw_comments": [
                "The scaling laws episode clarified why evals need to move faster than capability gains.",
                "Shared this with our research group. The section on interpretability was unusually practical.",
                "Lex asking the simple follow-up made the Andrej discussion much more useful.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177001"],
            "suggested_action": "Invite Alex to a private AI research Q&A and ask for topic feedback.",
        },
        {
            "handle": "@ml_nerd_42",
            "display_name": "Marco Ruiz",
            "bio": "ML engineer building ranking systems and writing technical threads.",
            "platforms": ["x"],
            "follower_count": 8100,
            "comment_count": 11,
            "reply_count": 7,
            "raw_comments": [
                "The reward modeling segment is exactly what my team is debating this week.",
                "This is the first explanation of synthetic data that did not feel hand-wavy.",
                "Would love a follow-up episode on practical eval harnesses.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177002"],
            "suggested_action": "Ask Marco for questions before the next technical AI interview.",
        },
        {
            "handle": "@sarah_chen_ai",
            "display_name": "Sarah Chen",
            "bio": "AI engineer at a health-tech startup, active in applied AI communities.",
            "platforms": ["x", "linkedin"],
            "follower_count": 9600,
            "comment_count": 8,
            "reply_count": 6,
            "raw_comments": [
                "The healthcare AI conversation needs exactly this level of nuance.",
                "I sent this episode to our product team before planning next quarter.",
                "The guest's answer on clinical trust was the highlight for me.",
            ],
            "source_urls": ["https://www.linkedin.com/feed/update/urn:li:activity:177003"],
            "suggested_action": "Invite Sarah to share healthcare AI questions for an upcoming guest.",
        },
        {
            "handle": "@devrel_marco",
            "display_name": "Marco Bellini",
            "bio": "Developer advocate focused on open source AI tooling.",
            "platforms": ["x", "linkedin"],
            "follower_count": 7200,
            "comment_count": 9,
            "reply_count": 4,
            "raw_comments": [
                "This thread is going straight into my workshop intro.",
                "The open-source tooling part was the best practical takeaway.",
                "Lex consistently gets builders to explain the tradeoffs clearly.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177004"],
            "suggested_action": "Ask Marco to co-host a builder-focused community session.",
        },
        {
            "handle": "@ux_nerd_kira",
            "display_name": "Kira Novak",
            "bio": "Product designer studying human trust in AI systems.",
            "platforms": ["x"],
            "follower_count": 5400,
            "comment_count": 7,
            "reply_count": 5,
            "raw_comments": [
                "The interface discussion around AI agents was underrated.",
                "Trust calibration is the missing layer in most AI product debates.",
                "This episode gave me language for a design review tomorrow.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177005"],
            "suggested_action": "Feature Kira's question in a future AI agents episode.",
        },
        {
            "handle": "@podcast_fan_jay",
            "display_name": "Jay Patel",
            "bio": "Long-time podcast listener, community organizer, and AI meetup host.",
            "platforms": ["x"],
            "follower_count": 3100,
            "comment_count": 10,
            "reply_count": 3,
            "raw_comments": [
                "Been listening since the early robotics interviews. This one is top five.",
                "Our meetup used the safety section as a discussion prompt.",
                "The closing question was a perfect bridge from technical to human.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177006"],
            "suggested_action": "Send Jay early discussion prompts for his meetup.",
        },
        {
            "handle": "@llm_builder_2",
            "display_name": "Nadia Petrova",
            "bio": "Founder building internal LLM tools for legal teams.",
            "platforms": ["linkedin"],
            "follower_count": 6800,
            "comment_count": 6,
            "reply_count": 4,
            "raw_comments": [
                "The enterprise adoption discussion matched what we see with legal workflows.",
                "Procurement is slower than model improvement, and this episode captured that tension.",
                "More episodes with builders who survived deployment would be useful.",
            ],
            "source_urls": ["https://www.linkedin.com/feed/update/urn:li:activity:177007"],
            "suggested_action": "Invite Nadia to a founder roundtable about deployed AI systems.",
        },
        {
            "handle": "@techwriter_ally",
            "display_name": "Ally Morgan",
            "bio": "Technical writer explaining AI infrastructure for non-specialists.",
            "platforms": ["x", "linkedin"],
            "follower_count": 11400,
            "comment_count": 5,
            "reply_count": 3,
            "raw_comments": [
                "This interview gave me the clearest analogy for eval drift.",
                "I quoted the deployment section in my newsletter today.",
                "The practical examples make this approachable without dumbing it down.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177008"],
            "suggested_action": "Offer Ally a transcript excerpt for her newsletter.",
        },
        {
            "handle": "@robotics_mina",
            "display_name": "Mina Ito",
            "bio": "Robotics PhD candidate working on embodied learning.",
            "platforms": ["x"],
            "follower_count": 4300,
            "comment_count": 6,
            "reply_count": 4,
            "raw_comments": [
                "The robotics detour was the hidden gem in this AI episode.",
                "Embodied learning deserves its own long-form conversation.",
                "The guest's answer on simulation gaps was refreshingly honest.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177009"],
            "suggested_action": "Ask Mina for robotics guests the audience should know.",
        },
        {
            "handle": "@policy_omar",
            "display_name": "Omar Haddad",
            "bio": "AI policy analyst tracking frontier model governance.",
            "platforms": ["linkedin"],
            "follower_count": 8900,
            "comment_count": 5,
            "reply_count": 4,
            "raw_comments": [
                "The governance discussion avoided the usual false binary.",
                "I appreciated the difference between model risk and deployment risk.",
                "This is useful context for our policy workshop next month.",
            ],
            "source_urls": ["https://www.linkedin.com/feed/update/urn:li:activity:177010"],
            "suggested_action": "Invite Omar to submit policy-focused audience questions.",
        },
        {
            "handle": "@founder_lena",
            "display_name": "Lena Ortiz",
            "bio": "Founder building AI copilots for customer support teams.",
            "platforms": ["x", "linkedin"],
            "follower_count": 15200,
            "comment_count": 4,
            "reply_count": 3,
            "raw_comments": [
                "The section on failure modes sounded exactly like our onboarding calls.",
                "This is the conversation I send to customers who overestimate automation.",
                "Would love more operators on the show.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177011"],
            "suggested_action": "Ask Lena for operator stories before a deployment-focused episode.",
        },
        {
            "handle": "@gradstudent_eli",
            "display_name": "Eli Park",
            "bio": "Graduate student studying mechanistic interpretability.",
            "platforms": ["x"],
            "follower_count": 2600,
            "comment_count": 8,
            "reply_count": 2,
            "raw_comments": [
                "This made the jump from circuits work to product risk much clearer.",
                "I used the interpretability explanation in our reading group.",
                "Please bring this guest back after their next paper.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177012"],
            "suggested_action": "Feature Eli's reading group question in a follow-up post.",
        },
        {
            "handle": "@community_rhea",
            "display_name": "Rhea Singh",
            "bio": "Runs a private AI builders community with weekly discussion groups.",
            "platforms": ["linkedin"],
            "follower_count": 4700,
            "comment_count": 7,
            "reply_count": 3,
            "raw_comments": [
                "Our members debated this episode for an hour after the session.",
                "The moderation style keeps the technical content accessible.",
                "This is the kind of conversation community builders need more often.",
            ],
            "source_urls": ["https://www.linkedin.com/feed/update/urn:li:activity:177013"],
            "suggested_action": "Invite Rhea to moderate a listener discussion thread.",
        },
        {
            "handle": "@data_victor",
            "display_name": "Victor Huang",
            "bio": "Data scientist focused on recommendation systems and content ranking.",
            "platforms": ["x"],
            "follower_count": 6100,
            "comment_count": 5,
            "reply_count": 2,
            "raw_comments": [
                "The ranking conversation applies to podcast discovery too.",
                "I wish more interviews connected recommender systems to creator incentives.",
                "The audience questions at the end were excellent.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177014"],
            "suggested_action": "Ask Victor for ranking-system questions before a platform episode.",
        },
        {
            "handle": "@security_ana",
            "display_name": "Ana Costa",
            "bio": "Security engineer working on AI threat modeling.",
            "platforms": ["x", "linkedin"],
            "follower_count": 9300,
            "comment_count": 4,
            "reply_count": 4,
            "raw_comments": [
                "The adversarial examples section should be mandatory listening for product teams.",
                "Security people and ML people still talk past each other. This helped.",
                "I clipped the deployment-risk answer for my team chat.",
            ],
            "source_urls": ["https://x.com/lexfridman/status/177015"],
            "suggested_action": "Invite Ana to submit security prompts for an AI safety guest.",
        },
    ]
    fans: list[FanProfile] = []
    for row in rows:
        profile = FanProfile(
            creator_handle=creator,
            source_tool=source_tool,  # type: ignore[arg-type]
            last_seen=now,
            cross_platform=len(row["platforms"]) > 1,
            **row,
        )
        fans.append(score_profile(profile))
    return fans
